### ISSUE TITLE
关于输出示例中打印顺序的问题

### ISSUE THREAD

**Issue by asdawej** [shangfengh/EESAST-hw2023-MultiThreading#4]
输出示例中，有四行是关于`Start()`的，后面接一个`bool`的打印. 其中，后两行涉及到`Thread.Sleep()`，因此打印顺序不必在意；但是前两行处于临界区，因此我出现了以下两种情形：

> - 第一种：与输出示例相同
> 
> <img src="https://asdawej.github.io/ELSE/%E6%AD%A3%E7%A1%AE.png"></img>
> 
> - 第二种：与输出示例相反
> 
> <img src="https://asdawej.github.io/ELSE/%E7%9B%B8%E5%8F%8D-1.png"></img>
> 
> 第三种：两处都刚好反过来：
> 
> <img src="https://asdawej.github.io/ELSE/%E7%9B%B8%E5%8F%8D-2.png"></img>
> 
> 第三种应该属于A和B都恰好结束`Thread.Sleep()`、到达临界区.

---

我的分析是，首先，`Start()`中存在一个锁；虽然线程A比线程B先调用`Thread.Start()`方法，但事实上，由于在`Main()`中调用两个线程这两句并没有明显的时间差，且两个线程实际上与`Main()`共用资源，因此并不必然确定线程A与线程B究竟谁先进入`Start()`锁.

另一方面，`Console.WriteLine("A Start: "+(a.Start(2000)).ToString());`这句并非原子操作，有可能出现线程A先执行`a.Start()`解锁、B执行并打印、A最后打印的情况.

---

为了验证这个情况，我设计了如下的实验：

```C#
using System;

class Program
{
    static void Main()
    {
        P o = new();
        new Thread(() =>
        {
            Console.WriteLine("A: " + o.f());
        }).Start();
        new Thread(() =>
        {
            Console.WriteLine("B: " + o.f());
        }).Start();
    }
}

class P
{
    private readonly object _lock = new();
    private int flag = 0;
    public int f()
    {
        lock (_lock)
        {
            return flag++;
        }
    }
}
```

实验结果如下：

> <img src="https://asdawej.github.io/ELSE/%E4%BD%90%E8%AF%81-1.png"></img> <img src="https://asdawej.github.io/ELSE/%E4%BD%90%E8%AF%81-2.png"></img>

在上锁的情况下，`flag`标识执行的次数，可以看到，确实出现了**先执行先打印**和**先执行后打印**两种情况.

---

综上所述，我认为在这两处`Start()`打印结果中，除了必然是一个`true`、一个`false`以外，不必然出现输出示例的情形.

不过，考虑到本次作业中还有代码逻辑的考虑，因此需要确定这样的分析在这里是否合适？

**Comment by shangfengh** [comment]
是这样的，所以只是示例而已
